### PR TITLE
Use the same ami as the instance that does the restart.

### PR DESCRIPTION
**Pull request by antban**
Right now during rolling-restart bubuku is trying to find some ami according to some filter that is hard coded in the bubuku code. 

This PR is making it different - the ami that is used on the instance will be used on all the other instances. 
The upgrade procedure is the following: 
1. upgrade ami on one of the instances.
2. run the rolling restart from that instance.

### CODE REVIEW

**Comment by antban** [comment]
:+

**Comment by a1exsh** [comment]
:+1:

**Comment by antban** [comment]
no changes, rebase only

**Comment by antban** [comment]
:+1:

**Comment by a1exsh** [comment]
:+1:

**Pull request merged**
