### PR TITLE
ARUHA-1389 add scalyr region to taupage

### PR DESCRIPTION
**Pull request by lmontrieux**
ARUHA-1389:     Migrate Scalyr to EU

## Description
This PR adds the scalyr_region property to taupage, if specified in the configuration file

### CODE REVIEW

**Comment by adyach** [comment]
@lmontrieux could you please update example configuration? https://github.com/zalando-nakadi/bubuku/blob/3bb5f727460afb00b9f20f5388d82b785ac716bf/instance_control/bubuku-1.json

**Comment by lmontrieux** [comment]
@adyach done in 5d9a641. I also updated the documentation in 64d2ae8 while I was at it.

**Comment by adyach** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Pull request merged**
