### PR TITLE
Upgrade Kafka binaries to 3.3.2

### PR DESCRIPTION
**Pull request by a1exsh**
Internal ticket: 1296

### CODE REVIEW

**Comment by a1exsh** [comment]
:+1:

**Comment by tor-vs-floki** [comment]
> 3.3.0
A significant bug was found in the 3.3.0 release after artifacts were pushed to Apache and Maven central but prior to the release announcement. As a result, the decision was made to not announce 3.3.0 and instead release 3.3.1 with the fix. It is recommended that 3.3.0 not be used.

Version 3.3.1 is the first released that was battle tested, and per our upgrade policy we want to use a version that is a following up of a battle tested one.

**Comment by a1exsh** [comment]
> Version 3.3.1 is the first released that was battle tested, and per our upgrade policy we want to use a version that is a following up of a battle tested one.

Good catch, thank you for spotting that!

**Comment by samizzy** [comment]
:+1:

**Comment by a1exsh** [comment]
:+1:

**Comment by samizzy** [comment]
:+1:

**Pull request closed without merging**
