### PR TITLE
Be able to swap leadership for loaded partitions in order to optimize network usage

### PR DESCRIPTION
**Pull request by antban**

### CODE REVIEW

**Comment by rcillo** [comment]
@antban I could not find the entry point for this code. Shouldn't there be a cli for this?

**Comment by antban** [comment]
There is no entry point yet, I was trying to fix problem on live environment, so it is not real command.
I was executing it thru unit test.

**Comment by rcillo** [comment]
👍

**Comment by antban** [comment]
No finished work here, nothing to review

**Pull request closed without merging**
